### ISSUE TITLE
Dockerless install guide

### ISSUE THREAD

**Issue by fidelix** [LTD-Beget/sprutio#84]
Can we have an alternative installation guide for people that can't use docker? There are many scenarios where docker is undesirable or impossible to use (for instance if you are using LXC containers on proxmox or if you are using a VPS that is LXC-based).

Just a general guide (being technical and succinct is fine) on which components you need to run sprut.io and how to glue everything together would be great.

**Comment by shadowlmd** [comment]
Just an opinion. I was against Docker at start and after about an hour of work had it running mostly, but the software is quite insecure and requires to be run as root for setuid() capability. This also required manual installation of several python modules that are not available from any repository, which means that you would have to maintain them manually. After looking at all this I made a decision that in this particular case Docker is a good thing. It provides good isolation and after tinkering with composer.json you can have this software almost completely isolated from your system, having access only to user files instead of whole root filesystem.

So, my strong opinion here is that no-one should want to run this outside of Docker unless they do not care about whole server security at all.

**Comment by fidelix** [comment]
@shadowlmd I'm sorry but that makes no sense at all.

Docker is one of the many different technologies you can use for the same thing and it's a particularly unwieldy one (there's a reason major hosters moved away from it).

I've used docker a lot before and I still do for a bunch of things (including software development) and automated tests

But there are places you can't run Docker at, and there are places where it doesn't make sense to do so.

```
So, my strong opinion here is that no-one should want to run this outside of Docker unless they do not care about whole server security at all.
```

You're entitled to your opinion and you may try to enforce it as the author of the application, but this seems like a needless restriction to place upon a software you seemingly desire to share with the community (being opensource and all).

There's a reason you won't find any relevant software in the wild that has a hard requirement on docker. This is genuinely the first time I've encountered this artificial requirement.

Also, what you're saying about server security and docker makes even less sense.
If you're not deploying docker correctly (something you have no way of enforcing in your Dockerfile) it is hardly more secure than a properly configured VM.

But again, you are the author and you are free to choose how you distribute your work.
It's a shame in my opinion as I was looking forward to trying your software but after your comment I really feel I shouldn't.

My strong opinion is that it is an ill-conceived idea to rely on Docker as a way to cover up for bad security and deployment practices.

Nonetheless I wish you the best of luck with your project, and thanks for the reply.

**Comment by shadowlmd** [comment]
I see your point. Just to clarify, I am not an author of this software and just wanted to share my opinion and warn other people seeking the way to run this outside of Docker. :)

**Comment by fidelix** [comment]
@shadowlmd apologies for mistaking you for the author.
